/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeken_com_jnews_jni_JNI */

#ifndef _Included_jeken_com_jnews_jni_JNI
#define _Included_jeken_com_jnews_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jeken_com_jnews_jni_JNI
 * Method:    getAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jeken_com_jnews_jni_JNI_getAppId
  (JNIEnv *, jclass);

/*
 * Class:     jeken_com_jnews_jni_JNI
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jeken_com_jnews_jni_JNI_getSecret
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
